const lang = {
    en: {
        home: 'Home',
        show: 'TV Shows',       
        latest: 'Latest',
        mylist: 'My List',
        signout: 'Sign Out',
        ai: "AI",
        search: "Search",
        clear: 'Clear',
        gptSearchPlaceholder: "What would you like to watch today?",
      },
      Hindi: {
        home: 'होम',
        show: 'टीवी शो', 
        latest: 'नवीनतम',
        mylist: 'मेरी सूची',
        signout: 'साइन आउट',
        ai: "AI",
        search: "खोज",
        clear: 'रीसेट',
        gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
      },
      Spanish: {
        home: 'Hogar',
        show: 'Programas',
        latest: 'El último',
        mylist: 'Mi lista',
        signout: 'Desconectar',
        ai: "AI",
        search: "buscar",
        clear: 'Claro',
        gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
      },
      French:{
        home: 'Maison',
        show: 'Émissions',
       latest: 'Dernier',
        mylist: 'Ma liste',
        signout: 'déconnecter',
        ai: "AI",
        search: 'Recherche',
        clear: 'Clair',
        gptSearchPlaceholder: "Qu’aimeriez-vous regarder aujourd’hui ?",
      },
      Japanese:{
        home: '家',
        show: 'テレビ番組',
        latest: '最新',
        mylist: '私のリスト',
        signout: '私のリスト',
        ai: "AI",
        search: '検索',
        clear: 'クリア',
        gptSearchPlaceholder: '今日は何を見たいですか？',
      }
};

export default lang;